version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - name: Change wrapper permissions
        run:
          command: chmod +x ./gradlew
      - name: Build with Gradle
        run:
          command: ./gradlew build
